# Generated by Django 4.0.4 on 2022-04-26 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_remove_powerconsumption_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='power_level',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
    ]
