# Generated by Django 4.0.4 on 2022-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_device_power_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorconsumption',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
