# Generated by Django 4.0.4 on 2022-04-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_alter_sectorconsumption_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='sectorconsumption',
            managers=[
            ],
        ),
    ]
